export const NAVIGATE_ABOUTPAGE='NAVIGATE_ABOUTPAGE';
export const NAVIGATE_CONTACTPAGE='NAVIGATE_CONTACTPAGE';
export const NAVIGATE_HOMEPAGE='NAVIGATE_HOMEPAGE';
export const NAVIGATE_SCHOOL='NAVIGATE_SCHOOL';
